"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { ActionButton, Drawer, Section, useToast } from "@willyu1007/web-workbench";
import { EntityRow } from "@willyu1007/web-workbench/list";
import type { ConsequenceDisclosure } from "@/lib/view/consequences";
import { FULLSCREEN_ACTIONS } from "@/lib/view/consequences";

export interface ConfirmTarget {
  /** What the action applies to, in the actor-safe wording the owner composed. */
  readonly summary: string;
  /** Concurrency head the command would carry as its expected version. */
  readonly expectedVersion: number;
  /** When the projection behind this screen was generated by the owner. */
  readonly revalidatedAt: string;
}

/**
 * The one confirmation surface. Both layouts render the same disclosure from the
 * same props — only the frame differs, so a reader never learns one action's
 * consequences in a shape that hides another's.
 *
 * Layout is not decided here. It is looked up from the action key so the mapping
 * has a single home; a component that guessed would scatter the policy.
 */
function Disclosure({
  disclosure,
  target,
  acknowledged,
  onAcknowledge,
}: {
  readonly disclosure: ConsequenceDisclosure;
  readonly target: ConfirmTarget;
  readonly acknowledged: boolean;
  readonly onAcknowledge: (next: boolean) => void;
}) {
  return (
    <>
      <p className="mt-value-label">
        重校验于 {target.revalidatedAt.slice(0, 16).replace("T", " ")} · 期望版本 v
        {target.expectedVersion}
      </p>

      <Section title="会立即发生">
        {disclosure.willHappen.map((line) => (
          <EntityRow key={line} model={{ title: line }} />
        ))}
      </Section>

      <Section title="不会发生">
        {disclosure.willNotHappen.map((line) => (
          <EntityRow key={line} model={{ title: line }} />
        ))}
      </Section>

      <Section title="影响范围">
        <EntityRow model={{ title: "目标", note: target.summary }} />
        <EntityRow
          model={{
            title: "可逆性",
            meta: [
              disclosure.reversible
                ? { text: "可再次调整", tone: "info" }
                : { text: "不可逆", tone: "danger" },
            ],
          }}
        />
      </Section>

      <label className="nurture-ack">
        <input
          type="checkbox"
          checked={acknowledged}
          onChange={(event) => onAcknowledge(event.target.checked)}
        />
        <span className="mt-body">{disclosure.acknowledgement}</span>
      </label>
    </>
  );
}

export function ConsequenceConfirm({
  disclosure,
  target,
  open,
  onClose,
}: {
  readonly disclosure: ConsequenceDisclosure | null;
  readonly target: ConfirmTarget;
  readonly open: boolean;
  readonly onClose: () => void;
}) {
  const [acknowledged, setAcknowledged] = useState(false);
  const [mounted, setMounted] = useState(false);
  const toast = useToast();

  useEffect(() => setMounted(true), []);

  if (disclosure === null) return null;
  const fullscreen = FULLSCREEN_ACTIONS.has(disclosure.actionKey);

  const close = () => {
    setAcknowledged(false);
    onClose();
  };

  // No command path exists yet: no scenario-service controller serves this
  // surface, and the capability is default-off. Saying so is the honest
  // outcome; a button that silently did nothing would read as success.
  const commit = () => {
    toast.notify(
      "info",
      "命令通道尚未接入",
      `${disclosure.title}：确认流程已走完，但 ${disclosure.actionKey} 的执行入口属于后端任务。`,
    );
    close();
  };

  // ActionButton exposes only primary and ghost, because the scene toolbar is
  // allowed exactly one navy pill. A confirmation footer is not the toolbar, and
  // the kit ships .mt-btn--danger for the destructive commit, so the button is
  // built from the kit's own classes rather than given a colour it withholds.
  const confirmButton = (
    <button
      type="button"
      className={`mt-btn ${disclosure.reversible ? "mt-btn--primary" : "mt-btn--danger"}${
        acknowledged ? "" : " mt-btn--disabled"
      }`}
      disabled={!acknowledged}
      onClick={commit}
    >
      {disclosure.confirmLabel}
    </button>
  );

  const body = (
    <Disclosure
      disclosure={disclosure}
      target={target}
      acknowledged={acknowledged}
      onAcknowledge={setAcknowledged}
    />
  );

  if (!fullscreen) {
    return (
      <Drawer
        open={open}
        onClose={close}
        title={disclosure.title}
        desc={`强确认 · ${disclosure.actionKey}`}
        footer={
          <>
            <ActionButton kind="ghost" onClick={close}>
              取消
            </ActionButton>
            {confirmButton}
          </>
        }
      >
        {body}
      </Drawer>
    );
  }

  if (!open || !mounted) return null;
  // Rendered through a portal because the kit's scene carries a transform, which
  // makes it the containing block for `position: fixed` — the panel would sit
  // inside the scene box and leave the nav reachable behind a supposedly modal
  // confirmation.
  return createPortal(
    <div className="nurture-fullscreen" role="dialog" aria-modal="true">
      <div className="nurture-fullscreen__inner">
        <p className="mt-value-label">强确认 · {disclosure.actionKey} · 不可逆</p>
        <h2 className="mt-h2">{disclosure.title}</h2>
        {body}
        <div className="nurture-fullscreen__actions">
          <ActionButton kind="ghost" onClick={close}>
            返回详情
          </ActionButton>
          {confirmButton}
        </div>
      </div>
    </div>,
    document.body,
  );
}
