import type { CanonicalRef } from "@my-chat/workflow-contracts";
import type { NurtureCaregiverWriteAuthority } from "./publish-process-transaction.js";

type DomainContextRef = CanonicalRef;

/** One stored lineage event, as the owner recorded it. */
export type NurtureStoredVisibilityEvent = {
  event_id: string;
  kind: string;
  reason_key: string;
  occurred_at: string;
  source_release_revision: number;
};

export type NurturePublicationSafetyWriteFacts = {
  authority: NurtureCaregiverWriteAuthority;
  /**
   * The exact role assignment the authorization validated. The lineage rows
   * name it — re-resolving inside finalize read a second clock and could
   * attribute the action to an assignment authorize never checked.
   */
  actor_role_assignment_id: string;
  publish_process_ref: DomainContextRef;
  publications: Array<{
    publication_id: string;
    /** Absent only for a release that somehow has no Receipt; refusal territory. */
    receipt_id?: string;
    release_revision: number;
    visibility: string;
    /** The stored lineage, oldest first. An idempotent repeat answers from it. */
    events: NurtureStoredVisibilityEvent[];
  }>;
};

/**
 * Canonical-owner writes behind the three post-release safety actions.
 *
 * The split matters: visibility transitions land in `apply`, but the lineage
 * rows carry `command_execution_id` — a foreign key to the execution row that
 * does not exist until after `apply` returns — so the events are appended by
 * `finalize`, inside the same transaction, once the execution is real. Row ids
 * are pre-generated by the command layer so `output_refs` can name rows the
 * finalizer has not written yet.
 */
export type NurturePublicationSafetyTransaction = {
  loadPublicationSafetyWriteFacts(input: {
    workspace_id: string;
    participant_id: string;
    process_key: string;
  }): Promise<NurturePublicationSafetyWriteFacts | null>;

  /** Monotone visibility transitions: visible → removed/redacted, removed → redacted. */
  applyPublicationVisibilityUpdate(input: {
    workspace_id: string;
    participant_id: string;
    updates: Array<{
      publication_id: string;
      from_visibility: string[];
      to_visibility: "removed" | "redacted";
    }>;
  }): Promise<{ updated_publication_ids: string[] }>;

  appendPublicationVisibilityEvents(input: {
    workspace_id: string;
    participant_id: string;
    command_execution_id: string;
    /** The load-time, authorize-validated assignment; never re-resolved here. */
    actor_role_assignment_id: string;
    events: Array<{
      event_id: string;
      publication_id: string;
      kind: "correction" | "target_removal" | "redaction";
      reason_key: string;
      source_release_revision: number;
      occurred_at: string;
      body_envelope?: unknown;
    }>;
  }): Promise<void>;
};
